version: "3.9"

services:
  node-app:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_REGION=${AWS_REGION}
      - ENABLE_CRON=${ENABLE_CRON}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - app-data:/usr/src/app/data
    restart: unless-stopped

volumes:
  app-data:
